version: '3'
services:
        web:
                build: 
                        context: /root/task
                        args:
                                - userid=1000
                ports:
                        - 80:9090
                container_name: saeed
                command: ["nginx"]
